/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dunkirk: typeof import('./src/components/Dunkirk.vue')['default']
    FeatureProcess: typeof import('./src/components/FeatureProcess.vue')['default']
    FeatureProcess2: typeof import('./src/components/FeatureProcess2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InputForm: typeof import('./src/components/InputForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavigationMenuIndicator: typeof import('radix-vue')['NavigationMenuIndicator']
    NavigationMenuLink: typeof import('radix-vue')['NavigationMenuLink']
    NavigationMenuList: typeof import('radix-vue')['NavigationMenuList']
    NavigationMenuListItem: typeof import('./src/components/NavigationMenuListItem.vue')['default']
    NavigationMenuRoot: typeof import('radix-vue')['NavigationMenuRoot']
    NavigationMenuViewport: typeof import('radix-vue')['NavigationMenuViewport']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableCard: typeof import('./src/components/ScrollableCard.vue')['default']
  }
}
